### ISSUE TITLE
Could you provide a readme document to use？

### ISSUE THREAD

**Issue by petrus091** [letrunghieu/laravel-menu#1]
Hello ， I find this repository ，and i don't known how to use?
So,Could you provide a readme document to use？

**Comment by letrunghieu** [comment]
Sure @HivenKay, I am writing the document for this package. I hope that the documentation can be completed today :smile: 

P/S: README is added.

**Comment by petrus091** [comment]
Thank you very  much,and some of your classes are very helpful to me.

**Comment by HivenKay** [comment]
closed #1
